### ISSUE TITLE
kannadaprabha.com

### ISSUE THREAD

**Issue by mediumkreation** [mediumkreation/IndianList#1]
**Request Type**
- [x] Filter Addition
- [ ] Other Issue
 
**URL found in**
```http://www.kannadaprabha.com/```

**What happens (screenshot)**
![kannadaprabha com_18-05-23 22 55 45](https://user-images.githubusercontent.com/39060814/41199781-70b11508-6cb5-11e8-89da-5cea1d703917.png)

**Your settings**
 * OS/version:
 * Browser/version:
 * Adblock Extension/version:

**Suggested Filter**
```
kannadaprabha.com##.div_main_right_banner_other
```

**Comment by monzta** [comment]
Looks good to me.
