### ISSUE TITLE
gujaratexclusive.in

### ISSUE THREAD

**Issue by DandelionSprout** [mediumkreation/IndianList#1602]
At `https://gujaratexclusive.in/harbhajan-singh-withdraw-from-ipl-2020/`, there are various ads for a hotel complex. 
![image](https://user-images.githubusercontent.com/22780683/92291593-b948d380-ef19-11ea-8c2d-7d6b26d29a0c.png)

I propose adding `||cdn.gujaratexclusive.in/wp-content/uploads/*.jpeg` to IndianList.

This was first pointed out to me in https://github.com/AdguardTeam/AdguardFilters/issues/63139.

**Comment by mediumkreation** [comment]
closed by: [#1681](https://github.com/mediumkreation/IndianList/pull/1681)
