### ISSUE TITLE
battinews.com

### ISSUE THREAD

**Issue by mediumkreation** [mediumkreation/IndianList#24]
Issue: Ads are links to Facebook posts of the website.
Found in URL: https://www.battinews.com

![battinews com_18-08-24 21 16 49](https://user-images.githubusercontent.com/39060814/44594867-fa636480-a7e4-11e8-9372-8f60edf0dfea.png)

**Suggested Filter**
```
battinews.com###HTML3
```

**Comment by sashachu** [comment]
This website can't be reached anymore, is it working for you?

**Comment by mediumkreation** [comment]
> This website can't be reached anymore, is it working for you?

Yes, I can still access it but now without 'https'  try, http://www.battinews.com/

**Comment by monzta** [comment]
Filter looks good to me.
