### ISSUE TITLE
Vavuniyanet.com

### ISSUE THREAD

**Issue by mediumkreation** [mediumkreation/IndianList#28]
**Issue:** 
This is an ad but posted as a blog post/page/url.

Found in URL: Vavuniyanet.com
![vavuniyanet com_18-08-26 19 12 08](https://user-images.githubusercontent.com/39060814/44628797-05dd9980-a965-11e8-876c-a128ac0182f9.png)

**Comment by sashachu** [comment]
Looks like they can be blocked by blocking gifs in the sidebar with something like this: `vavuniyanet.com##.main-sidebar .textwidget [src$=".gif"]`.

**Comment by mediumkreation** [comment]
> Looks like they can be blocked by blocking gifs in the sidebar with something like this: `vavuniyanet.com##.main-sidebar .textwidget [src$=".gif"]`.

Should these be treated as Adserve ?  as they are directly lined to a detail/description page.

secondly the suggested filter will also block non-ad content in the page. so we have to be more specific.

**suggested filter**

```
||vavuniyanet.com^*Advent$image
||vavuniyanet.com^*Poonthottam$image
```

![image](https://user-images.githubusercontent.com/39060814/46367598-a4af9100-c69b-11e8-93de-e191bcb65035.png)

**Comment by monzta** [comment]
```
||vavuniyanet.com^*Advent$image
||vavuniyanet.com^*Poonthottam$image
```
Looks good to me
