### ISSUE TITLE
lankamurasu.com

### ISSUE THREAD

**Issue by mediumkreation** [mediumkreation/IndianList#29]
This seems to me an Ad, but has a totally different way of representation. Resembling as an Author's info. 

Found in URL: http://www.lankamurasu.com/2854/
![lankamurasu com_18-08-30 19 57 06](https://user-images.githubusercontent.com/39060814/44858415-90890600-ac8f-11e8-9816-de5632b9170d.png)

**Comment by monzta** [comment]
https://github.com/mediumkreation/IndianList/commit/b6161f9203b2faaff7e6ff807986207b85ff3118
