### ISSUE TITLE
 telugupeople.com

### ISSUE THREAD

**Issue by mediumkreation** [mediumkreation/IndianList#33]
### Issue 1
This is a 3rd-party widget that has ads along with widget content.

**Found in URL**: http://telugupeople.com/news/article_00106850_2000_Premiere_shows_for_Bharat_Ane_Nenu.asp
![telugupeople com_18-09-02 15 33 13](https://user-images.githubusercontent.com/39060814/44954787-c9aabb80-aec5-11e8-86a7-fb087b8ca8ea.png)

### Issue 2
The Ad serve content is almost embedded into markup.

![telugupeople com_18-09-02 15 27 46](https://user-images.githubusercontent.com/39060814/44954843-b2200280-aec6-11e8-924c-cea386235a53.png)

**Suggested Filter**
```
telugupeople.com#?#table:-abp-has(> tbody > tr > td > a:-abp-contains(Advertisements))
```

**Comment by sashachu** [comment]
To block the ad in the widget you could block the image `||cricket.widgets.stats.com/widget_banner$image` or something like `cricket.widgets.stats.com##[href*="f1pulse.com"]`.

For the second issue it is better to use a regular hiding filter like `telugupeople.com##TABLE[style="BORDER-BOTTOM: #000000 1px solid;BORDER-TOP: #000000 1px solid;BORDER-LEFT: #000000 1px solid;BORDER-RIGHT: #000000 1px solid;"][width="302"]`.

**Comment by mediumkreation** [comment]
Stale
