### ISSUE TITLE
banglanews24.com

### ISSUE THREAD

**Issue by DandelionSprout** [mediumkreation/IndianList#3322]
A `PandaMart` video ad and a thin placeholder near the top. Especially noticeable with a phone user agent. I initially learned about this from https://github.com/AdguardTeam/AdguardFilters/issues/87242. Notably, the ad is *not* present on the site's English version, only on the Bengali version.

I propose:
```
banglanews24.com##.ads
||banglanews24.com/public/banner^
```

![image](https://user-images.githubusercontent.com/22780683/124277698-a2790a80-db45-11eb-904f-bd61380c3622.png)

Adblockers: uBlock Origin 1.36.1b1 + I Don't Care About Cookies 3.3.1
Browser: Chrome 91.0.4472.124 x64
Lists in use: ↓
![image](https://user-images.githubusercontent.com/22780683/124277895-da804d80-db45-11eb-8da3-df15ab234882.png)

**Comment by mediumkreation** [comment]
resolve by #3585
