### ISSUE TITLE
https://raag.fm/

### ISSUE THREAD

**Issue by felippesantos46** [mediumkreation/IndianList#4042]
Hey there !

So i've noticed some redirect popups at [raag](https://raag.fm/)

Proposed filter: `||pendulumtemporary.com^$third-party`

Screenshot:
<img width="1440" alt="Screenshot 2021-11-05 at 14 02 46" src="https://user-images.githubusercontent.com/65717387/140514598-3002dc95-2af2-4469-b846-bdda3854e7e8.png">

**Comment by ghajini** [comment]
Hello @felippesantos46
Use Ublock origin by gorhill 
https://github.com/gorhill/uBlock

**Comment by mediumkreation** [comment]
this should be filed in [easylist](https://github.com/easylist/easylist)
