### ISSUE TITLE
Ads are not blocking on adult sites

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#4255]
**Steps to reproduce:**
1. Launch browser -> Enable adbloker from menu 
2. load  hdtube.porn / xhamster16.desi / hdpornmax.com / hdporn24.org

**Actual Behavior:** Ads are not blocking on adult sites
**Expected Behavior:** Ads should be blocking on adult sites

**OS:** Android 11
**Tyep:** JioPages(Mobile Browser)
**Active Filter lists:** Indian filter-lists 
**Location:** India-> Karnataka
**Screeshots:**

**Comment by mediumkreation** [comment]
Moved to easylist

**Comment by JioPagesMobile** [comment]
Is this issue is fixed ?

**Comment by mediumkreation** [comment]
@JioPagesMobile you can track it here.. https://github.com/easylist/easylist/issues/10321
