### ISSUE TITLE
atalsamachar.com - typo

### ISSUE THREAD

**Issue by krystian3w** [mediumkreation/IndianList#4347]
https://github.com/mediumkreation/IndianList/blob/f92d6ca71f7b4289533ad1713aec9a866648395a/IndianList/specific_hide.txt#L2373

filter line lost `##` by uknown reason in https://github.com/mediumkreation/IndianList/commit/8b107a0638dd8b5f50935c12e4fa779de62ae084#diff-d33d50c47d0d3cc866b69ad9f3201dc349475088bab78432c698c4e7b3873521R2342 (missed by many people eyes).

**Comment by mediumkreation** [comment]
resolved #4357
