### ISSUE TITLE
Ads are blocked but blank space is not removed on news18 sub domain sites

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#4359]
Steps to reproduce:

Launch browser -> Enable adbloker from menu
load https://jionewsapi.media.jio.com
https://www.news18.com
https://kannada.news18.com
https://hindi.news18.com
https://lokmat.news18.com
https://gujarati.news18.com
https://telugu.news18.com
https://tamil.news18.com
https://malayalam.news18.com
https://bengali.news18.com
https://punjab.news18.com
https://urdu.news18.com
https://assam.news18.com
https://odia.news18.com
Try scrolling up & down
Actual Behavior: Ads are blocked but blank space is not removed
Expected Behavior: Blank space should be removed, once hide ads

OS: Android 11
Tyep: JioPages(Mobile Browser)
Active Filter lists: Indian filter-lists
Location: India-> Karnataka
Screeshots:

https://hindi.news18.com
![screen_29-12-2021_11_55_51](https://user-images.githubusercontent.com/95853886/147633734-0375eb33-befd-4e20-9f9c-65e5ca6621b5.png)

https://gujarati.news18.com
![screen_29-12-2021_11_57_34](https://user-images.githubusercontent.com/95853886/147633753-5dc2f76c-7558-4960-9615-4479a3c9b4c9.png)

https://lokmat.news18.com
![screen_29-12-2021_11_57_45](https://user-images.githubusercontent.com/95853886/147633763-3c61ce0e-e975-418e-8053-68d5843eb845.png)

https://telugu.news18.com
![screen_29-12-2021_11_58_18](https://user-images.githubusercontent.com/95853886/147633769-63c99053-a275-4874-8168-8ece5390e4ec.png)

https://tamil.news18.com
![screen_29-12-2021_11_58_28](https://user-images.githubusercontent.com/95853886/147633790-ccd2022a-08cf-428a-aa00-454fcf0cc2bd.png)

https://kannada.news18.com
![screen_29-12-2021_11_58_39](https://user-images.githubusercontent.com/95853886/147633796-65753201-8a0b-4446-b717-b8f92619bc59.png)

https://malayalam.news18.com
![screen_29-12-2021_11_59_03](https://user-images.githubusercontent.com/95853886/147633807-319efe9f-c8dd-446e-8f21-dab0d943cb24.png)

https://bengali.news18.com
![screen_29-12-2021_11_59_15](https://user-images.githubusercontent.com/95853886/147633818-88d2b158-89f3-4ac7-8270-372d827ce1ae.png)

https://punjab.news18.com
![screen_29-12-2021_11_59_26](https://user-images.githubusercontent.com/95853886/147633825-ec9cfaf7-e582-4ceb-9ac8-146706dcce9f.png)

https://assam.news18.com
![screen_29-12-2021_12_00_08](https://user-images.githubusercontent.com/95853886/147633831-e8283a94-02e4-469f-a8f2-b53ea9c7165e.png)

https://odia.news18.com
![screen_29-12-2021_12_00_19](https://user-images.githubusercontent.com/95853886/147633834-135d370c-87e7-4034-befe-1426c39316e7.png)

**Comment by mediumkreation** [comment]
resolved. #4392 , #4391
