### ISSUE TITLE
Ads are blocked but blank space is not removed on jionews.com

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#4360]
Steps to reproduce:

Launch browser -> Enable adbloker from menu
load jionews.com
Try scrolling up & down
Actual Behavior: Ads are blocked but blank space is not removed
Expected Behavior: Blank space should be removed, once hide ads

OS: Android 11
Tyep: JioPages(Mobile Browser)
Active Filter lists: Indian filter-lists
Location: India-> Karnataka
Screeshots:
![screen_29-12-2021_12_09_21](https://user-images.githubusercontent.com/95853886/147634338-11cb88ad-1322-45d2-8bfe-c5e7dfb5cf99.png)
![screen_29-12-2021_12_09_30](https://user-images.githubusercontent.com/95853886/147634344-3bad6782-801a-4e78-b4b0-cf6dcbeb98cb.png)
![screen_29-12-2021_12_09_38](https://user-images.githubusercontent.com/95853886/147634346-c486247c-204b-4473-9fde-d1c772420ac2.png)
![screen_29-12-2021_12_10_15](https://user-images.githubusercontent.com/95853886/147634347-7c27627e-9cc4-4e84-afeb-43954bcc8c65.png)
![screen_29-12-2021_12_10_52](https://user-images.githubusercontent.com/95853886/147634350-90c5575a-ed2a-463c-9453-547d95e13814.png)

**Comment by mediumkreation** [comment]
resolved. #4392 , #4391
