### ISSUE TITLE
http://www.achhisoch.com

### ISSUE THREAD

**Issue by mediumkreation** [mediumkreation/IndianList#5]
**Request Type**
- [x] Filter Addition
- [ ] Other Issue

**Description**
All the below looks to be Ad Serve

![achhisoch com_18-07-30 21 41 05](https://user-images.githubusercontent.com/39060814/43413087-ad5f047e-944c-11e8-92f0-b4f9c9c06152.png)
![achhisoch com_18-07-30 21 41 31](https://user-images.githubusercontent.com/39060814/43413089-ad943d60-944c-11e8-8acd-a067dd7a1be8.png)
![achhisoch com_18-07-30 21 41 39](https://user-images.githubusercontent.com/39060814/43413090-adc763ca-944c-11e8-89ff-e3913329f55a.png)
![achhisoch com_18-07-30 21 41 50](https://user-images.githubusercontent.com/39060814/43413091-adf775b0-944c-11e8-89c8-03e42a66d15f.png)

**Your settings**
 * OS/version:
 * Browser/version:
 * Adblock Extension/version:

**Suggested Filter**
```

achhisoch.com###text-18
achhisoch.com###text-24
achhisoch.com###text-25
achhisoch.com##a[href*="newzoninfotech.com"] img:only-child
||wp.com/www.achhisoch.com/wp-content/uploads/2018/07/ad-sidebar.jpg
||wp.com/www.achhisoch.com*/newzoninfotech$image
||wp.com/www.achhisoch.com/wp-content/uploads/2018/07/banner-top.jpg

```

**Comment by mediumkreation** [comment]
@monzta , these Ads might be of the Developer/company who owns this site.
was unable to directly link the two, so created a defect for discussion.

**Comment by monzta** [comment]
Doesn't look like that to me. But what makes you think so?

**Comment by mediumkreation** [comment]
Its pure guess, that's how Indian IT/web startups do marketing. 
but If you think this should be removed I will Add them to the list.
I hope you reviewed the filters too :)

**Comment by monzta** [comment]
Ok, think it's ok to add them. 

Regarding the filters: instead the `2018/07` part I would probably use a `*` but other than that it looks good to me.

**Comment by mediumkreation** [comment]
Fixed
PullRequest: [#7](https://github.com/mediumkreation/IndianList/pull/7)
