### ISSUE TITLE
Ads are blocked but blank space is not removed on republicworld.com

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#5002]
Steps to reproduce:

Launch browser -> Enable adbloker from menu
load (https://m.republicworld.com/india-news/general-news/ambedkar-jayanti-2022-date-history-significance-heres-everything-you-need-to-know-articleshow.html)

Try scrolling up & down
Actual Behavior: Ads are blocked but blank space is not removed
Expected Behavior: Blank space should be removed, once hide ads

OS: Android 11
Tyep: JioPages(Mobile Browser)
Active Filter lists: Indian filter-lists
Location: India-> Karnataka
Screeshots:

![screen_14-04-2022_15_35_55](https://user-images.githubusercontent.com/95853886/163365280-12f550d4-2a55-44cd-8210-4c207f697cb4.png)

![screen_14-04-2022_15_36_09](https://user-images.githubusercontent.com/95853886/163365309-0204f69b-1e56-413b-9444-13ed775e39b8.png)

**Comment by mediumkreation** [comment]
Closed: [#11666](https://github.com/easylist/easylist/pull/11666)

**Comment by JioPagesMobile** [comment]
Fixed
