### ISSUE TITLE
Ads are blocked but blank space is not removed on jionews.com

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#5003]
Steps to reproduce:

Launch browser -> Enable adbloker from menu
load (https://jionews.com/home/article/10/1373430368/Higher-Faster-Further-The-New-BMW-F-900-XR-Launched-in-India?source=jiopages)

Try scrolling up & down
Actual Behavior: Ads are blocked but blank space is not removed
Expected Behavior: Blank space should be removed, once hide ads

OS: Android 11
Tyep: JioPages(Mobile Browser)
Active Filter lists: Indian filter-lists
Location: India-> Karnataka
Screeshots:
![screen_14-04-2022_15_50_31](https://user-images.githubusercontent.com/95853886/163366036-d1ad83be-8cb9-4ea8-ac1f-acbadc525152.png)

**Comment by mediumkreation** [comment]
closed: [#11665](https://github.com/easylist/easylist/pull/11665)

**Comment by JioPagesMobile** [comment]
Fixed
