### ISSUE TITLE
nethgossip.lk

### ISSUE THREAD

**Issue by DandelionSprout** [mediumkreation/IndianList#5062]
An ad for `idak.lk` in the upper right on `http://nethgossip.lk/` and `http://nethnews.lk/`, as well as an invisible placeholder on bottom that prevents clicking on articles. Additionally, there's a strange animated image in the lower left on `http://nethgossip.lk/` that could possibly be an ad. The websites are in Sinhalese. I propose:
```
nethgossip.lk,nethnews.lk###ads_hide
||nethnews.lk/public/images/awurudu^$subdocument
```
* Environment: uBlock Origin 1.42.4 + I Don't Care About Cookies 3.3.8 + Chrome 100.0.4896.127 x64 + Windows 11 x64
* Screenshot:
<details>

![image](https://user-images.githubusercontent.com/22780683/165276354-12ffd46f-e72d-4b39-b613-42de1659372e.png)

</details>

* Lists in use:
<details>

![image](https://user-images.githubusercontent.com/22780683/165277116-f1cebccf-fbde-4028-89f7-a22783fe31e7.png)

</details>

**Comment by mediumkreation** [comment]
Closed: 
 - [#5068](https://github.com/mediumkreation/IndianList/pull/5068) 
 - [#5067](https://github.com/mediumkreation/IndianList/pull/5067)
