### ISSUE TITLE
mithimedia.in

### ISSUE THREAD

**Issue by DandelionSprout** [mediumkreation/IndianList#5063]
Two ads on the rightside bar at `https://www.mithimedia.in/`. I propose `mithimedia.in##.Image.widget`

Although Maithili is not currently among the supported languages at https://github.com/mediumkreation/IndianList#specialization, I felt it was worth a try to suggest adding support for it, because then IndianList would cover not just India and Sri Lanka's languages, but also Nepal's two main languages.

* Environment: uBlock Origin 1.42.4 + I Don't Care About Cookies 3.3.8 + Chrome 100.0.4896.127 x64 + Windows 11 x64
* Screenshot:
<details>

![image](https://user-images.githubusercontent.com/22780683/165281142-1c715aae-975f-4fe0-b862-887bdd23855a.png)

</details>

* Lists in use:
<details>

![image](https://user-images.githubusercontent.com/22780683/165277116-f1cebccf-fbde-4028-89f7-a22783fe31e7.png)

</details>

**Comment by mediumkreation** [comment]
@DandelionSprout we are already supporting Nepalis languages and all Nepal Sites... Maithili is part of Indian language list and we are already supporting it.

Closed: [#5066](https://github.com/mediumkreation/IndianList/pull/5066)
