### ISSUE TITLE
Hide ad space on https://kannada.news18.com  [JioPages]

### ISSUE THREAD

**Issue by edivaniadc** [mediumkreation/IndianList#5085]
Can you please hide 1 in-feed ad space on https://kannada.news18.com/  

**Steps to reproduce:**
Browser: JioPages
ABP Lists: [IndianList+EasyList (minified)]( https://easylist-downloads.adblockplus.org/indianlist+easylist-minified.txt)

Chrome selector:
`#__next > div > div:nth-child(10) > div.newstrendvideo-box > ul > li:nth-child(7) > div > div.myad.adunitContainer`
<img width="189" alt="kn18" src="https://user-images.githubusercontent.com/57706597/165813503-dba05756-6ec3-4919-9233-67718f95d80b.png">

**Comment by mediumkreation** [comment]
closed: [#5086](https://github.com/mediumkreation/IndianList/pull/5086)
