### ISSUE TITLE
prothomalo.com (ads)

### ISSUE THREAD

**Issue by SeriousHoax** [mediumkreation/IndianList#5400]
Ads on: `https://www.prothomalo.com/`

Browser: Chrome, Firefox
OS: Windows 11 Pro
Adblocker: uBO
Filters: Default uBO, EasyList, EasyPrivacy, Fanboy's Annoyances, Anti-Facebook, IndianList

After seeing the first ad on the homepage which may not look like an ad at first glance, scroll down a bit to see the other two like the attached images below.

![1](https://user-images.githubusercontent.com/29574622/176023725-544776ea-fb2f-416a-91e5-d81e60dec41a.png)

![2](https://user-images.githubusercontent.com/29574622/176023737-0fe5b7ee-fa0c-4edc-a1c8-9b2fb634a76c.png)

**Comment by mediumkreation** [comment]
fixed : #5408
