### ISSUE TITLE
eisamay.com

### ISSUE THREAD

**Issue by SeriousHoax** [mediumkreation/IndianList#5457]
Ads, annoyance and leftovers on: `https://eisamay.com/sports/cricket/news/joe-root-set-multiple-records-on-the-day-he-lost-to-india/articleshow/92694212.cms`
Browser: Firefox
OS: Windows 11 Pro
Adblocker: uBO
Filters: Default uBO, EasyList, EasyPrivacy, Anti-Facebook, Adguard Annoyance, IndianList
Screenshot:
![z](https://user-images.githubusercontent.com/29574622/177510740-ed943358-b803-4541-81b2-bc4f33ea5903.png)

**Comment by mediumkreation** [comment]
resolved #5475
