### ISSUE TITLE
inews.zoombangla.com

### ISSUE THREAD

**Issue by SeriousHoax** [mediumkreation/IndianList#5458]
Ads on: `https://inews.zoombangla.com/%E0%A6%9A%E0%A6%BE%E0%A6%B2%E0%A7%81-%E0%A6%B9%E0%A6%9A%E0%A7%8D%E0%A6%9B%E0%A7%87-%E0%A7%AC-%E0%A6%B2%E0%A7%87%E0%A6%A8%E0%A7%87%E0%A6%B0-%E0%A6%95%E0%A6%BE%E0%A6%B2%E0%A6%A8%E0%A6%BE-%E0%A6%B8/`
Browser: Firefox
OS: Windows 11 Pro
Adblocker: uBO
Filters: Default uBO, EasyList, EasyPrivacy, Anti-Facebook, Adguard Annoyance, IndianList
Screenshot:
![1](https://user-images.githubusercontent.com/29574622/177511449-322ece75-2443-4560-9dde-88f8f31a8776.png)

**Comment by mediumkreation** [comment]
resolved #5462
