### ISSUE TITLE
prothomalo.com

### ISSUE THREAD

**Issue by SeriousHoax** [mediumkreation/IndianList#5469]
Ads on: `https://www.prothomalo.com/`
Browser: Firefox
OS: Windows 11 Pro
Adblocker: uBO
Filters: Default uBO, EasyList, EasyPrivacy, Anti-Facebook, Adguard Annoyance, IndianList
Screenshot:
![fi](https://user-images.githubusercontent.com/29574622/177729327-8047593f-7e3c-4416-8936-418511b55f4e.gif)

**Comment by mediumkreation** [comment]
resolved : #5489
