### ISSUE TITLE
jagonews24.com

### ISSUE THREAD

**Issue by SeriousHoax** [mediumkreation/IndianList#5470]
Empty ads placeholder: `https://www.jagonews24.com/amp/775698`
Browser: Firefox, Firefox for Android
OS: Windows 11 Pro
Adblocker: uBO
Filters: Default uBO, EasyList, EasyPrivacy, Anti-Facebook, Adguard Annoyance, IndianList
Screenshot:
![z](https://user-images.githubusercontent.com/29574622/177731736-b2ff7560-372a-4f3c-bf2b-5f43756935af.png)

**Comment by mediumkreation** [comment]
resolved #5473
