### ISSUE TITLE
[JioPages]Blank Spaces And grey Box with Blank Box is Showing in add blocks

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#5768]

**Comment by JioPagesMobile** [comment]
Issue1   -> ABP turned On Mode  Blank space getting Created  With Rotating  loading Icon
Website  https://www.yovizag.com/  (HomePage)

Issue 2  (Alexa NewsSite) Blank Space getting created  in add block 

Site https://www.teluguglobal.com/ (HomePage)


Issue 3-> Blank space getting created  with  , ads loading logo 
Website https://www-asianage-com.cdn.ampproject.org/v/s/www.asianage.com/amp?amp_js_v\u003d0.1\u0026usqp\u003dmq331AQKKAFQArABIIACAw%3D%3D


Issue 4> ADWall not showing . But On Blocking the Add white Color Box is showing  at bottom in add place
Website  https://indianexpress.com/ (HomePage)


Issue 4  Blank Box gets Created in add block



Website [www.ndtv.com](http://www.ndtv.com/) (Home page)


 Issue 5–   Grey color box getting created
Website https://www.google.com/amp/s/www.udayavani.com/


Issue 6 > After Add block these two highlighted adds are still showing
Website [www.oneindia.com](http://www.oneindia.com/)  (Home 
[addblock.docx](https://github.com/mediumkreation/IndianList/files/9442673/addblock.docx)
Page)
[addblock.docx](https://github.com/mediumkreation/IndianList/files/9443836/addblock.docx)
[](url)

Issue 7
In Money control Page  after Add block , adds are showing
Website [www.moneycontrol.com](http://www.moneycontrol.com/)  (Home page)

**Comment by JioPagesMobile** [comment]
[addblock.docx](https://github.com/mediumkreation/IndianList/files/9443877/addblock.docx)

**Comment by mediumkreation** [comment]
https://github.com/easylist/easylist/pull/17689
https://github.com/easylist/easylist/pull/17690
