### ISSUE TITLE
[JioPages] Brave is not showing adwall but adwall is shown in jiopages 

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#6691]
Turn on ABP on Jio Pages and try to access Following sites 

https://www.thehindubusinessline.com/
https://www.sonyliv.com/
https://www.sportskeeda.com/
https://www.thehindu.com/
https://www.thehindubusinessline.com/

**Comment by mediumkreation** [comment]
This should be filed against Brave Browser.
https://github.com/brave/brave-browser
