### ISSUE TITLE
[JioPages] Ad blocks count is more in JioPages compared to Brave

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#6693]
Enable ABP in Jio Pages
Load following  Url 
https://Godaddy.com
https://Adobe.com
https://Amazon.in

**Comment by JioPagesMobile** [comment]
https://user-images.githubusercontent.com/95853886/215439946-12f2f65c-f16e-4342-9015-fb49a291d9aa.mp4

(attached video for reference)

**Comment by mediumkreation** [comment]
Sorry, but this seems to be out of scope for us. 
We can't compare Brave and JioPages.
