### ISSUE TITLE
[JioPages] Jio Cinema Videos are getting Blocked by Ad blocker

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#6703]
1.Enable ABP
2 Open Jio cinema
3 Try to play any video
![Screenshot_20230124_142006](https://user-images.githubusercontent.com/95853886/215467086-6fb8a1f1-f647-4b41-99fc-4b0ee7e80ecf.jpg)

**Comment by mediumkreation** [comment]
disable abp and also disable generic webbrowser adblocker.
