### ISSUE TITLE
[JioPages] "Taboola Feed" text is showing when ABP is enabled , Text should get removed

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#6704]
Precondition : Acceptable ads turned off
Secure mode is turned Off

Lunch Jio Pages
 Turn on ABP
Load page  of https://indianexpress.com/ or NDTV

Check for ads 
![IMG_20230130_172521](https://user-images.githubusercontent.com/95853886/215471340-48ecaa6c-7001-420e-ab59-da63e67913ec.jpg)

**Comment by mediumkreation** [comment]
This is not an Ad.

**Comment by JioPagesMobile** [comment]
Here ad is removed, but taboola ad text is remained. please check on Jiopages from playstore

**Comment by JioPagesMobile** [comment]
@mediumkreation  Issue still observed in ndtv Home Page  " Taboola text " Even after ad Hide (attached video)

https://user-images.githubusercontent.com/95853886/216243005-c17242af-f0ba-44f6-83e2-5476f2ff9b88.mp4

**Comment by mediumkreation** [comment]
@JioPagesMobile Taboola Feed not always feed Advertisement, it also feed content.
