### ISSUE TITLE
[JioPages] LIC ad is not getting removed when ABP is turned on and acceptable ads turned Of

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#6706]
Turn of acceptable ads
Turn on APB and secure mode

https://m.cricbuzz.com/cricket-commentary/60000/ind-vs-nz-2nd-t20i-new-zealand-tour-of-india-2023

![Screenshot_20230130_191354](https://user-images.githubusercontent.com/95853886/215495610-7f8c6faa-0816-4b04-acee-8d8cfd1366c0.jpg)

**Comment by mediumkreation** [comment]
no longer showing up.
