### ISSUE TITLE
[JioPages] Sometimes Acceptable ads showing in some of the webpage

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#6709]
Turn on ABP 
Load www.ndtv.com and 
https://www.freepressjournal.in/

**Comment by mediumkreation** [comment]
will need reproducible steps and URL.

**Comment by JioPagesMobile** [comment]
@mediumkreation Issue still observed on www.ndtv.com Url page .after enabling ABP and loading ndtv page sponsored ads are showing attached video , please check the video[](url)

https://user-images.githubusercontent.com/95853886/216239845-64789999-8cf4-470e-b074-cbaa1a8edf53.mp4
