### ISSUE TITLE
[JioPages]  Blank space is showing ad place in AMP Pages 

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#6739]
enable ABP and secure Mode
load below page

https://www.google.com/amp/s/m.timesofindia.com/business/budget/union-budget-2023-a-new-house-for-commons-major-tax-relieffor-the-rich-too/amp_articleshow/97535360.cms

 
![Screenshot_20230206_095311](https://user-images.githubusercontent.com/95853886/216883860-8d39a024-e794-448e-bd10-42ace6697296.jpg)

**Comment by mediumkreation** [comment]
not reproducible

**Comment by JioPagesMobile** [comment]
@mediumkreation  Always reproduciable please check this on Jiopages app from playstore 

![screen_08-02-2023_11_46_54](https://user-images.githubusercontent.com/95853886/217450108-75405062-b579-46aa-893e-b5617d55d3f7.png)
