### ISSUE TITLE
andhrajyothy.com

### ISSUE THREAD

**Issue by DandelionSprout** [mediumkreation/IndianList#7087]
Various ads and a transparent bottom banner on `https://www.andhrajyothy.com/`. This was brought to my attention through https://github.com/AdguardTeam/AdguardFilters/issues/147599. I propose:
```
andhrajyothy.com##.container-fluid > .container > div
andhrajyothy.com##section[class] div[style^="text-align : "]
andhrajyothy.com##.stickyAds
```
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/230539406-e6be77e9-cdc0-4f6e-9614-64e6fa8d6534.png)

</details>

* Adblockers: uBlock Origin 1.48.4 + I Don't Care About Cookies 3.4.6
* Browser: Chrome 111.0.5563.148 x64
* OS: Windows 11 22H2 x64
<details><summary>Lists in use during testing:</summary>

![image](https://user-images.githubusercontent.com/22780683/230539608-fca72ea2-a775-45ed-8935-d148335a9aa2.png)

</details>

**Comment by mediumkreation** [comment]
#70796
