### ISSUE TITLE
channel24bd.tv

### ISSUE THREAD

**Issue by SeriousHoax** [mediumkreation/IndianList#7312]
Ad on: `https://www.channel24bd.tv/`
Browser: Chrome Latest
Adblocker: uBO Latest
Filters: Default uBO+Indian List
Screenshot: 
![image](https://github.com/mediumkreation/IndianList/assets/29574622/872e2e27-7126-4374-8e49-2abf3abf4495)

**Comment by mediumkreation** [comment]
fixed:  #7322
