### ISSUE TITLE
haal.fashion

### ISSUE THREAD

**Issue by MF-Debug** [mediumkreation/IndianList#7506]
One transparent ad banner is appearing on the front page of the website while browsing via both mobile and desktop browser (firefox nightly)

On Mobile:
![Screenshot_20230614-141106_Firefox_Nightly](https://github.com/mediumkreation/IndianList/assets/6173607/6a26d5d5-c8e9-4a7a-911c-69ac029098c0)

Ad-blockers: uBlock Origin v1.50.0 + Enhanced Tracking protection of Firefox (standard)
Browser: Firefox Nightly latest 32-bit
Device & OS: Samsung galaxy note 3 SM-N9005, official LOS 18.1

On Desktop:
![image](https://github.com/mediumkreation/IndianList/assets/6173607/f0c010a0-255b-4c2a-a49a-0ea127f4d9d2)

Adblockers: uBlock Origin v1.50.0 + Enhanced Tracking protection of Firefox (standard)
Browser: Firefox Nightly latest 64-bit
OS: Windows 10 21H2 x64

Lists in use during testing:
![image](https://github.com/mediumkreation/IndianList/assets/6173607/bb859d02-63d3-4bc7-ac4c-1dce45b21411)
![image](https://github.com/mediumkreation/IndianList/assets/6173607/21c117bd-ee11-49b3-b6b2-3eb6f2c0a16e)

**Comment by mediumkreation** [comment]
fixed: ##7509

**Comment by MF-Debug** [comment]
> fixed: ##7509

This broke the website completely. See the below screenshot from mobile browser. The whole website content except the footer is gone.
![Screenshot_20230617-022542_Firefox_Nightly](https://github.com/mediumkreation/IndianList/assets/6173607/0f654e62-1092-454e-8fb5-0b9b7bb0a0f0)

same on desktop browser as well. I can see the website properly after disabling the list from ublock origin filter lists.

**Comment by MF-Debug** [comment]
This seems to be fixed automatically, ignore it.
