### ISSUE TITLE
(Ads and Distraction ) Pricehistoryapp dot com

### ISSUE THREAD

**Issue by cleanerspam** [mediumkreation/IndianList#7651]
> ! 2023-07-11 https://pricehistoryapp.com
pricehistoryapp.com##.lg\:px-5.px-3.lg\:items-center.gap-x-3.lg\:flex-row.flex-col.flex.shadow-md.bg-\[\#0088cc\].py-4
||pricehistoryapp.com/_next/image?url=https%3A%2F%2Fcdn.pricehistory.in%2Fmedia%2Fbanners%2Fprice-history.webp&w=*&q=75$image
pricehistoryapp.com##.min-h-\[280px\]
pricehistoryapp.com##.dots
pricehistoryapp.com##div.py-2.mx-auto.content-width:nth-of-type(2)
||pricehistoryapp.com/_next/image?url=https%3A%2F%2Fcdn.pricehistory.in%2Fmedia%2Fbanners%2Fprice-history.webp&w=*&q=75$image
||pricehistoryapp.com/_next/image?url=https%3A%2F%2Fcdn.pricehistory.in%2Fmedia%2Fbanner$image
||pricehistoryapp.com/_next/image?url=%2Fimages%2Fdownload-ios.png&w=*&q=75$image
pricehistoryapp.com##.xl\:h-96.h-\[600px\].relative.flex-col.flex.w-full.bg-purple-50 > .p-10
pricehistoryapp.com##.xl\:h-96.h-\[600px\].relative.flex-col.flex.w-full.bg-purple-50
pricehistoryapp.com##.relative.xl\:h-96.h-\[600px\].flex-row.flex.w-full.bg-purple-50 > .self-center.bottom-0.xl\:right-0.xl\:w-96.xl\:h-96.h-96.w-full.absolute > span
pricehistoryapp.com##.relative.xl\:h-96.h-\[600px\].flex-row.flex.w-full.bg-purple-50 > .p-10
pricehistoryapp.com##.relative.xl\:h-96.h-\[600px\].flex-row.flex.w-full.bg-purple-50 > .self-center.bottom-0.xl\:right-0.xl\:w-96.xl\:h-96.h-96.w-full.absolute
pricehistoryapp.com##.relative.xl\:h-96.h-\[600px\].flex-row.flex.w-full.bg-purple-50
pricehistoryapp.com##.py-12.mt-20.dark\:border-gray-600.border-t
pricehistoryapp.com##.content-width.content\:px-0.px-3.pt-16
pricehistoryapp.com##.mt-5.lg\:px-0.px-3.mx-auto.content-width > .md\:text-3xl.font-bold.text-2xl.w-full
pricehistoryapp.com##.mt-5.lg\:px-0.px-3.mx-auto.content-width > p
pricehistoryapp.com##.leading-6.w-full.mt-8.mx-auto.py-10.px-3.content-width
pricehistoryapp.com##div.h-full.cursor-pointer.keen-slider__slide > span
pricehistoryapp.com##div.h-full.cursor-pointer.keen-slider__slide:nth-of-type(1)
pricehistoryapp.com##div.h-full.cursor-pointer.keen-slider__slide:nth-of-type(2)
pricehistoryapp.com##.lg\:h-\[370px\].sm\:h-80.h-48.z-0.keen-slider
pricehistoryapp.com##.mt-5.lg\:px-0.px-3.mx-auto.content-width > .dark\:text-gray-300.text-gray-600.xl\:w-2\/3.md\:w-4\/5.w-full
pricehistoryapp.com##.cursor-pointer.px-4.space-y-2.hover\:border-primary-300.dark\:border-gray-800.border-gray-200.border.justify-center.items-center.flex-col.flex.dark\:bg-primary-800.bg-primary-50.h-\[295px\]
pricehistoryapp.com##.mt-3.gap-2.xl\:grid-cols-5.lg\:grid-cols-4.md\:grid-cols-3.sm\:grid-cols-2.grid-cols-1.grid
pricehistoryapp.com##.content\:px-3.px-3.mt-8.space-y-2.flex-col.flex.w-full.content-width > .indiana-scroll-container--native-scroll.indiana-scroll-container--hide-scrollbars.indiana-scroll-container.scroll-container.overflow-x-auto.space-x-3.flex-row.flex.w-full
pricehistoryapp.com##.content\:px-3.px-3.mt-5.space-y-2.flex-col.flex.w-full.content-width > .font-semibold.text-xl
pricehistoryapp.com##.content\:px-3.px-3.mt-8.space-y-2.flex-col.flex.w-full.content-width > .font-semibold.text-xl
pricehistoryapp.com##.content\:px-3.px-3.mt-5.space-y-2.flex-col.flex.w-full.content-width
pricehistoryapp.com##h2.font-semibold.text-lg:nth-of-type(4)
pricehistoryapp.com##h2.font-semibold.text-lg:nth-of-type(3)
pricehistoryapp.com##h2.font-semibold.text-lg:nth-of-type(2)
pricehistoryapp.com##.mt-3.font-semibold.text-lg
pricehistoryapp.com##.justify-center.space-x-3.items-center.flex-row.flex > .font-bold.text-3xl
pricehistoryapp.com##.space-x-2.items-center.flex-row.flex.font-semibold.text-white.hover\:border-primary-500.border-transparent.border.hover\:bg-primary-600.bg-primary-500.py-1.px-3
pricehistoryapp.com##div.py-2.mx-auto.content-width:nth-of-type(4)

**Comment by cleanerspam** [comment]
![IMG_20230711_165622](https://github.com/mediumkreation/IndianList/assets/59386233/4607f129-ea14-4885-b819-e519be20f0b1)
After filters

**Comment by mediumkreation** [comment]
no longer an issue.
