### ISSUE TITLE
[JioPages] Ad space is not removed on https://statusqueen.com/whatsapp-dp

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#7956]
Launch app load https://statusqueen.com/whatsapp-dp

![image](https://github.com/mediumkreation/IndianList/assets/95853886/76c87549-b6c0-4a00-8196-00081e21ec19)

**Comment by mediumkreation** [comment]
no longer reproducible.

**Comment by JioPagesMobile** [comment]
Till reproducible on latest jiosphere playstore build
