### ISSUE TITLE
[JioPages] gamil ads are not removed from desktop vision of webpage  

### ISSUE THREAD

**Issue by JioPagesMobile** [mediumkreation/IndianList#8154]
**PreCondition:**
Turn on Adblock and secure mode
Turn off acceptable ads

**Steps:**
1. Launch jiopages app -> load gmail.com -> enable desktop view 
2. Check of ads 

![image](https://github.com/mediumkreation/IndianList/assets/95853886/ae2393be-e20e-4778-bb5e-4383b2c16044)

**Comment by JioPagesMobile** [comment]
@mediumkreation please check this

**Comment by mediumkreation** [comment]
@JioPagesMobile this should be filed under  Easylist.
