### ISSUE TITLE
The inclusion of Sri Lanka (Sinhala: සිංහල) in this list is inaccurate.

### ISSUE THREAD

**Issue by rafalefighter** [mediumkreation/IndianList#9222]
This block list appears to contain domains related to India. However, in the readme, it mentions that Sri Lanka (Sinhala: සිංහල) is also included. Sri Lanka is a separate country and not part of India, nor is it related in any way. If someone wanted to block Indian content but is based in Sri Lanka, this filter would block most Sri Lankan local websites as well.

Can we move the list of Sri Lankan websites (mostly TLD .lk) out of this and create a separate list?

Thanks

**Comment by mediumkreation** [comment]
Firstly, we do not block content but focus only on Advertisements. 
Secondly, our list is region specific and we have grouped our filter-list  on language and not political boundaries.

Fell free to report sites in Sinhala( සිංහල)  language that you think has Advertisements.

Thanks
