### ISSUE TITLE
telecom.economictimes.indiatimes.com : Signup nuisance

### ISSUE THREAD

**Issue by Ramar121** [mediumkreation/IndianList#9757]
![Screenshot 2024-07-05 125936](https://github.com/mediumkreation/IndianList/assets/146962304/6299a7d2-dc20-46e3-a17e-11372aa26dce)

Getting the signup nuisances in https://telecom.economictimes.indiatimes.com/

**Comment by mediumkreation** [comment]
Newsletter Signup popups are not Ads.
